print("Hello, world!".upper())

print("  |  |  ")
print("  |  |  ")
print("  |  |  ")
print("--------")
print("  |  |  ")
print("  |  |  ")
print("  |  |  ")
print("--------")
print("  |  |  ")
print("  |  |  ")
print("  |  |  ")
